spring:
  application:
    name: IDENTITY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jwtsql:3306/jwtgateway
    username: root
    password: Password
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone : http://swiggy-service-registry:8761/eureka/
server:
  port: 9898

logging:
  level:
    org.springframework.security: trace