spring:
  application:
    name: order-poller

  datasource:
    url: jdbc:mysql://localhost:3306/outbox_db
    username: outbox_user
    password: outbox_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

order:
  poller:
    topic:
      name: not-processed-messages
