services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: javatechie
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  keySetPaging:
    build:
      context: .
      dockerfile: Dockerfile
    image: keyset-paging
    container_name: keyset-paging-container
    restart: always
    ports:
      - "9191:9191"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local
