eureka:
  client:
    service-url:
      defaultZone : http://swiggy-service-registry:8761/eureka/
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # issuer-uri: http://identity-service:8080/realms/springboot-microservice-realm
          jwk-set-uri: http://identity-service:8080/realms/springboot-microservice-realm/protocol/openid-connect/certs
