spring:
  application:
    name: authorization-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
logging:
  level:
    org.springframework.security: TRACE
server:
  port: 9000