CREATE TABLE IF NOT EXISTS STOCK (
    id         BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(255),
    quantity   INT
);

INSERT INTO STOCK (product_name, quantity) VALUES ('Apple iPhone 15', 120);
INSERT INTO STOCK (product_name, quantity) VALUES ('Samsung Galaxy S24', 95);
INSERT INTO STOCK (product_name, quantity) VALUES ('Sony WH-1000XM5 Headphones', 60);
INSERT INTO STOCK (product_name, quantity) VALUES ('Apple MacBook Pro 14"', 45);
INSERT INTO STOCK (product_name, quantity) VALUES ('Dell XPS 15 Laptop', 38);
INSERT INTO STOCK (product_name, quantity) VALUES ('LG 27" 4K Monitor', 72);
INSERT INTO STOCK (product_name, quantity) VALUES ('Logitech MX Master 3 Mouse', 150);
INSERT INTO STOCK (product_name, quantity) VALUES ('Keychron K2 Keyboard', 88);
INSERT INTO STOCK (product_name, quantity) VALUES ('iPad Pro 12.9"', 55);
INSERT INTO STOCK (product_name, quantity) VALUES ('Google Pixel 8', 67);
INSERT INTO STOCK (product_name, quantity) VALUES ('Nintendo Switch OLED', 110);
INSERT INTO STOCK (product_name, quantity) VALUES ('PlayStation 5 Console', 30);
INSERT INTO STOCK (product_name, quantity) VALUES ('Xbox Series X', 25);
INSERT INTO STOCK (product_name, quantity) VALUES ('GoPro Hero 12', 42);
INSERT INTO STOCK (product_name, quantity) VALUES ('DJI Mini 4 Pro Drone', 18);
INSERT INTO STOCK (product_name, quantity) VALUES ('Apple Watch Series 9', 80);
INSERT INTO STOCK (product_name, quantity) VALUES ('Samsung Galaxy Watch 6', 65);
INSERT INTO STOCK (product_name, quantity) VALUES ('Fitbit Charge 6', 93);
INSERT INTO STOCK (product_name, quantity) VALUES ('Bose QuietComfort 45', 54);
INSERT INTO STOCK (product_name, quantity) VALUES ('JBL Flip 6 Speaker', 130);
INSERT INTO STOCK (product_name, quantity) VALUES ('Amazon Echo Dot 5th Gen', 200);
INSERT INTO STOCK (product_name, quantity) VALUES ('Google Nest Hub 2nd Gen', 75);
INSERT INTO STOCK (product_name, quantity) VALUES ('Apple AirPods Pro 2nd Gen', 140);
INSERT INTO STOCK (product_name, quantity) VALUES ('Samsung 65" QLED TV', 20);
INSERT INTO STOCK (product_name, quantity) VALUES ('LG OLED 55" TV', 15);
INSERT INTO STOCK (product_name, quantity) VALUES ('Razer DeathAdder V3 Mouse', 110);
INSERT INTO STOCK (product_name, quantity) VALUES ('SteelSeries Arctis Nova Pro', 48);
INSERT INTO STOCK (product_name, quantity) VALUES ('ASUS ROG Zephyrus G14', 33);
INSERT INTO STOCK (product_name, quantity) VALUES ('Lenovo ThinkPad X1 Carbon', 40);
INSERT INTO STOCK (product_name, quantity) VALUES ('HP Spectre x360 14"', 36);
INSERT INTO STOCK (product_name, quantity) VALUES ('Microsoft Surface Pro 9', 50);
INSERT INTO STOCK (product_name, quantity) VALUES ('Kindle Paperwhite 11th Gen', 160);
INSERT INTO STOCK (product_name, quantity) VALUES ('Canon EOS R50 Camera', 28);
INSERT INTO STOCK (product_name, quantity) VALUES ('Sony Alpha A7 IV Camera', 14);
INSERT INTO STOCK (product_name, quantity) VALUES ('Nikon Z30 Camera', 22);
INSERT INTO STOCK (product_name, quantity) VALUES ('Anker 65W USB-C Charger', 250);
INSERT INTO STOCK (product_name, quantity) VALUES ('Belkin MagSafe Charger', 180);
INSERT INTO STOCK (product_name, quantity) VALUES ('Samsung 1TB SSD T7', 95);
INSERT INTO STOCK (product_name, quantity) VALUES ('WD 2TB External HDD', 85);
INSERT INTO STOCK (product_name, quantity) VALUES ('Seagate 4TB Backup Plus', 60);
INSERT INTO STOCK (product_name, quantity) VALUES ('TP-Link AX3000 Wi-Fi Router', 70);
INSERT INTO STOCK (product_name, quantity) VALUES ('Netgear Nighthawk AX12', 35);
INSERT INTO STOCK (product_name, quantity) VALUES ('Corsair Vengeance 32GB RAM', 100);
INSERT INTO STOCK (product_name, quantity) VALUES ('G.Skill Trident Z5 16GB RAM', 88);
INSERT INTO STOCK (product_name, quantity) VALUES ('NVIDIA RTX 4070 GPU', 12);
INSERT INTO STOCK (product_name, quantity) VALUES ('AMD Radeon RX 7800 XT GPU', 10);
INSERT INTO STOCK (product_name, quantity) VALUES ('Intel Core i9-13900K CPU', 25);
INSERT INTO STOCK (product_name, quantity) VALUES ('AMD Ryzen 9 7950X CPU', 20);
INSERT INTO STOCK (product_name, quantity) VALUES ('ASUS ROG Maximus Z790 Motherboard', 18);
INSERT INTO STOCK (product_name, quantity) VALUES ('Cooler Master MasterLiquid 360L', 44);
INSERT INTO STOCK (product_name, quantity) VALUES ('Noctua NH-D15 CPU Cooler', 55);
INSERT INTO STOCK (product_name, quantity) VALUES ('EVGA SuperNOVA 850W PSU', 40);
INSERT INTO STOCK (product_name, quantity) VALUES ('Fractal Design Meshify 2 Case', 30);
INSERT INTO STOCK (product_name, quantity) VALUES ('Lian Li O11 Dynamic Case', 28);
INSERT INTO STOCK (product_name, quantity) VALUES ('BenQ ZOWIE 24" 144Hz Monitor', 62);
INSERT INTO STOCK (product_name, quantity) VALUES ('AOC 27" Curved Gaming Monitor', 47);
INSERT INTO STOCK (product_name, quantity) VALUES ('Wacom Intuos Pro Tablet', 35);
INSERT INTO STOCK (product_name, quantity) VALUES ('Elgato Stream Deck MK.2', 58);
INSERT INTO STOCK (product_name, quantity) VALUES ('Blue Yeti USB Microphone', 90);
INSERT INTO STOCK (product_name, quantity) VALUES ('Rode NT-USB Mini Microphone', 72);
INSERT INTO STOCK (product_name, quantity) VALUES ('Logitech C920 Webcam', 115);
INSERT INTO STOCK (product_name, quantity) VALUES ('Razer Kiyo Pro Webcam', 68);
INSERT INTO STOCK (product_name, quantity) VALUES ('Elgato 4K60 Pro Capture Card', 22);
INSERT INTO STOCK (product_name, quantity) VALUES ('AVerMedia Live Gamer 4K', 17);
INSERT INTO STOCK (product_name, quantity) VALUES ('Ubiquiti UniFi AP WiFi 6', 45);
INSERT INTO STOCK (product_name, quantity) VALUES ('Synology DS923+ NAS', 12);
INSERT INTO STOCK (product_name, quantity) VALUES ('Raspberry Pi 5 4GB', 200);
INSERT INTO STOCK (product_name, quantity) VALUES ('Arduino Uno R4 WiFi', 175);
INSERT INTO STOCK (product_name, quantity) VALUES ('Philips Hue Starter Kit', 85);
INSERT INTO STOCK (product_name, quantity) VALUES ('LIFX Smart Bulb 4-Pack', 130);
INSERT INTO STOCK (product_name, quantity) VALUES ('TP-Link Kasa Smart Plug', 220);
INSERT INTO STOCK (product_name, quantity) VALUES ('Ring Video Doorbell 4', 55);
INSERT INTO STOCK (product_name, quantity) VALUES ('Arlo Pro 4 Security Camera', 40);
INSERT INTO STOCK (product_name, quantity) VALUES ('Eufy RoboVac 11S Robot Vacuum', 32);
INSERT INTO STOCK (product_name, quantity) VALUES ('iRobot Roomba j7+', 18);
INSERT INTO STOCK (product_name, quantity) VALUES ('Dyson V15 Detect Vacuum', 24);
INSERT INTO STOCK (product_name, quantity) VALUES ('Instant Pot Duo 7-in-1', 95);
INSERT INTO STOCK (product_name, quantity) VALUES ('Ninja Foodi Air Fryer XL', 78);
INSERT INTO STOCK (product_name, quantity) VALUES ('Breville Barista Express', 30);
INSERT INTO STOCK (product_name, quantity) VALUES ('Nespresso Vertuo Next', 65);
INSERT INTO STOCK (product_name, quantity) VALUES ('KitchenAid Stand Mixer 5Qt', 42);
INSERT INTO STOCK (product_name, quantity) VALUES ('Vitamix 5200 Blender', 20);
INSERT INTO STOCK (product_name, quantity) VALUES ('Theragun Prime Massager', 55);
INSERT INTO STOCK (product_name, quantity) VALUES ('Hyperice Hypervolt 2 Pro', 38);
INSERT INTO STOCK (product_name, quantity) VALUES ('Garmin Forerunner 965', 45);
INSERT INTO STOCK (product_name, quantity) VALUES ('Polar Vantage V3 Watch', 27);
INSERT INTO STOCK (product_name, quantity) VALUES ('Oculus Quest 3 VR Headset', 22);
INSERT INTO STOCK (product_name, quantity) VALUES ('Sony PlayStation VR2', 16);
INSERT INTO STOCK (product_name, quantity) VALUES ('Anker PowerBank 26800mAh', 190);
INSERT INTO STOCK (product_name, quantity) VALUES ('Mophie Powerstation Plus', 145);
INSERT INTO STOCK (product_name, quantity) VALUES ('Spigen iPhone 15 Case', 300);
INSERT INTO STOCK (product_name, quantity) VALUES ('OtterBox Defender Series Case', 260);
INSERT INTO STOCK (product_name, quantity) VALUES ('Samsung Galaxy Buds 2 Pro', 88);
INSERT INTO STOCK (product_name, quantity) VALUES ('Nothing Ear 2 Earbuds', 75);
INSERT INTO STOCK (product_name, quantity) VALUES ('Tile Pro Bluetooth Tracker', 210);
INSERT INTO STOCK (product_name, quantity) VALUES ('Apple AirTag 4-Pack', 165);
INSERT INTO STOCK (product_name, quantity) VALUES ('Crucial BX500 480GB SSD', 120);
INSERT INTO STOCK (product_name, quantity) VALUES ('Kingston 64GB USB 3.2 Flash Drive', 400);
