x-common:
  &x-common
  image: postgres:15
  user: postgres
  restart: always
  networks:
    - my-network
  healthcheck:
    test: 'pg_isready -U user --dbname=postgres'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres-primary:
    <<: *x-common
    ports:
      - 5432:5432
    networks:
      - micro-net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres 
      -c wal_level=replica 
      -c hot_standby=on 
      -c max_wal_senders=10 
      -c max_replication_slots=10 
      -c hot_standby_feedback=on
    volumes:
      - ./00_init.sql:/docker-entrypoint-initdb.d/00_init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d demo && psql -U postgres -d demo -c 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-replica:
    <<: *x-common
    ports:
      - 5433:5432
    environment:
      PGUSER: replicator
      PGPASSWORD: postgres_user_for_db_read
    networks:
      - micro-net
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=postgres-primary --port=5432
      do
      echo 'Waiting for primary to connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      postgres-primary:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d demo && psql -U postgres -d demo -tAc 'SELECT pg_is_in_recovery()' | grep -q t" ]
      interval: 10s
      timeout: 5s
      retries: 10
  multi-source:
    build:
      context: ./origin-multi-data-source
      dockerfile: Dockerfile
    image: multi-data-source-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - micro-net
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy

networks:
  micro-net:
