spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: golf-client
          client-secret: golf-secret
          introspection-uri: http://localhost:9000
intro-spect:
  uri: http://localhost:9000/oauth2/introspect
server:
  port: 8081
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web.client.RestTemplate: DEBUG
