spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: golf-client
          client-secret: golf-secret
          introspection-uri: http://authorization-server:9000
intro-spect:
  uri: http://authorization-server:9000/oauth2/introspect
server:
  port: 8081