spring:
  security:
    oauth2:
      client:
        registration:
          golf-client:
            provider: golf-provider
            client-id: golf-client
            client-secret: golf-secret
            authorization-grant-type: client_credentials
            scope: read
        provider:
          golf-provider:
            token-uri: http://authorization-server:9000/oauth2/token
resource-server:
  url: http://resource-server:8081/lessons