spring:
  application:
    name: oauthorization
  security:
    oauth2:
      authorizationserver:
        issuer: http://oauthorization:9000
server:
  port: 9000
logging:
  level:
    org.springframework.security: TRACE
app:
  redirect:
    uri: http://localhost:8080/login/oauth2/code/nghia-client